FROM python:3.10.6

WORKDIR /usr/app

ARG METEOMATICS_API_URL
ARG METEOMATICS_USER
ARG METEOMATICS_PASSWORD
ARG OPENMETEO_API_URL

ENV METEOMATICS_API_URL=$METEOMATICS_API_URL
ENV METEOMATICS_USER=$METEOMATICS_USER
ENV METEOMATICS_PASSWORD=$METEOMATICS_PASSWORD
ENV OPENMETEO_API_URL=$OPENMETEO_API_URL

COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /usr/app/src
